name = "cv-rafael"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cv_database"
database_id = "7fe78f75-e84e-4207-b6dd-399791b6bb48"

# Service binding to Cloudflare Pages project
[[services]]
binding = "ASSETS"
service = "ChispartCV"

[vars]
BLACKBOX_API_KEY = "sk-mgu31y6sPid25HyDyFFNMg"

# Cron trigger for checking trial expirations every hour
[triggers]
crons = ["0 * * * *"]
